version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    ports:
      - "8081:8083"  
    container_name: app
    depends_on:
      - db
    # environment:
    #   - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/moves
    #   - SPRING_DATASOURCE_USERNAME=compose-postgres
    #   - SPRING_DATASOURCE_PASSWORD=compose-postgres
    #   - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
    #   - SPRING_JPA_HIBERNATE_DDL_AUTO=create
  db:
    image: 'postgres:13.1-alpine' 
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=moves
    # volumes:
    # - ./postgres-data:/var/lib/postgresql/data
    # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql  
    # - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql  