kind: Deployment
apiVersion: apps/v1
metadata:
  name: servicelogin-vault2
  namespace: test
  annotations:
  labels:
    app: servicelogin-vault2
    app.kubernetes.io/component: servicelogin-vault2
    app.kubernetes.io/instance: servicelogin-vault2
    app.kubernetes.io/name: servicelogin-vault2
    app.kubernetes.io/part-of: service-login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicelogin-vault2
  template:
    metadata:
      annotations: 
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'issues'
        vault.hashicorp.com/agent-inject-secret-config: 'secret/data/issues/config'
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/issues/config" -}}
          export SPRING_DATASOURCE_USERNAME="{{ .Data.data.dbuser }}"
          export SPRING_DATASOURCE_PASSWORD="{{ .Data.data.dbpwd }}"
          {{- end -}}
      labels:
        app: servicelogin-vault2
        deployment: servicelogin-vault2
    spec:
      serviceAccountName: issues
      containers:
        - name: servicelogin-vault2
          image: >-
            quay.io/vishwanath_puranik/slogin@DIGEST
