apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: servicelogin-vault2
    app.kubernetes.io/component: servicelogin-vault2
    app.kubernetes.io/instance: servicelogin-vault2
    app.kubernetes.io/name: servicelogin-vault2
    app.kubernetes.io/part-of: service-login-app
  name: servicelogin-vault2
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicelogin-vault2
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-config: secret/data/issues/config
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/issues/config" -}}
          export SPRING_DATASOURCE_USERNAME="{{ .Data.data.dbuser }}"
          export SPRING_DATASOURCE_PASSWORD="{{ .Data.data.dbpwd }}"
          {{- end -}}
        vault.hashicorp.com/role: issues
      labels:
        app: servicelogin-vault2
        deployment: servicelogin-vault2
    spec:
      containers:
      - args:
        - source /vault/secrets/config && echo $SPRING_DATASOURCE_USERNAME && sleep
          600
        command:
        - sh
        - -c
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://172.30.50.249:5432/moves?createDatabaseIfNotExist=true
        - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
          value: org.postgresql.Driver
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        image: quay.io/vishwanath_puranik/slogin@sha256:25e8583285d22df5ef760abd2d5e7191db9e35a63852fbe8d2b2fd7be8373324
        name: servicelogin-vault2
      serviceAccountName: issues
