apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slogin-vault2
  namespace: test
spec:
  destination:
    namespace: test
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: ./gitops/dev
    repoURL: 'https://github.com/vishwanath-puranik/moves-gh-actions.git'
    targetRevision: HEAD

